const { contextBridge, ipcRenderer } = require('electron');
const on=(channel,cb)=>{const fn=(_e,d)=>cb(d);ipcRenderer.on(channel,fn);return()=>ipcRenderer.removeListener(channel,fn)};
contextBridge.exposeInMainWorld('qwen', {
  chooseFolder:()=>ipcRenderer.invoke('choose-folder'), setProjectFolder:p=>ipcRenderer.invoke('set-project-folder',p), chooseTrustedFolder:()=>ipcRenderer.invoke('choose-trusted-folder'), trustedRoots:()=>ipcRenderer.invoke('trusted-roots'), workspaceStatus:()=>ipcRenderer.invoke('workspace-status'),
  tree:p=>ipcRenderer.invoke('tree',p||'.'), readFile:p=>ipcRenderer.invoke('read-file',p), writeFile:(p,c)=>ipcRenderer.invoke('write-file',p,c), editFile:(p,o,n)=>ipcRenderer.invoke('edit-file',p,o,n), undoLastChange:()=>ipcRenderer.invoke('undo-last-change'), searchFiles:(p,x)=>ipcRenderer.invoke('search-files',p,x||'.'), searchContent:(p,x)=>ipcRenderer.invoke('search-content',p,x||'.'),
  runCommand:c=>ipcRenderer.invoke('run-command',c), startBackground:(c,l)=>ipcRenderer.invoke('start-background',c,l), pauseBackground:id=>ipcRenderer.invoke('pause-background',id), resumeBackground:id=>ipcRenderer.invoke('resume-background',id), stopBackground:id=>ipcRenderer.invoke('stop-background',id), backgroundList:()=>ipcRenderer.invoke('background-list'), backgroundStatus:id=>ipcRenderer.invoke('background-status',id),
  gitStatus:()=>ipcRenderer.invoke('git-status'), gitDiff:()=>ipcRenderer.invoke('git-diff'), gitBranches:()=>ipcRenderer.invoke('git-branches'), gitCheckout:b=>ipcRenderer.invoke('git-checkout',b), gitCommit:m=>ipcRenderer.invoke('git-commit',m), gitInit:()=>ipcRenderer.invoke('git-init'), gitPullUpdate:()=>ipcRenderer.invoke('git-pull-update'), gitRemotes:()=>ipcRenderer.invoke('git-remotes'), devUpdate:()=>ipcRenderer.invoke('dev-update'),
  runRegressionSuite:()=>ipcRenderer.invoke('run-regression-suite'), checkpointCreate:()=>ipcRenderer.invoke('checkpoint-create'), checkpointInfo:()=>ipcRenderer.invoke('checkpoint-info'), checkpointRollback:()=>ipcRenderer.invoke('checkpoint-rollback'), sessionLoad:()=>ipcRenderer.invoke('session-load'), sessionSave:d=>ipcRenderer.invoke('session-save',d), projectContext:()=>ipcRenderer.invoke('project-context'),
  getConfig:()=>ipcRenderer.invoke('get-config'), setModel:m=>ipcRenderer.invoke('set-model',m), listModels:()=>ipcRenderer.invoke('list-models'), chat:p=>ipcRenderer.invoke('ollama-chat',p), chatStream:p=>ipcRenderer.invoke('ollama-chat-stream',p),
  webSearch:q=>ipcRenderer.invoke('web-search',q), fetchUrl:u=>ipcRenderer.invoke('fetch-url',u), githubSearch:q=>ipcRenderer.invoke('github-search',q), npmInfo:n=>ipcRenderer.invoke('npm-info',n), openUrl:u=>ipcRenderer.invoke('open-url',u),
  onChatChunk:cb=>on('ollama-chunk',cb), onWorkspaceSelected:cb=>on('workspace-selected',cb), onTerminalChunk:cb=>on('terminal-chunk',cb), onBackgroundEvent:cb=>on('background-event',cb), ping:()=>ipcRenderer.invoke('ping'), cancelChat:()=>ipcRenderer.invoke('cancel-chat')
});
